import { IEmployee } from "../../interface/IEmployee";

export const employeesData: IEmployee[] = [
  {
    id: 1,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    full_name: "John Doe",
    email: "john.doe@example.com",
    role: "Software Engineer",
    manager_id: 2,
  },
  {
    id: 2,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    full_name: "Jane Smith",
    email: "jane.smith@example.com",
    role: "Product Manager",
    manager_id: 2,
  },
  {
    id: 3,
    image: null,
    full_name: "Michael Johnson",
    email: "michael.johnson@example.com",
    role: "UX Designer",
    manager_id: 1,
  },
  {
    id: 4,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    full_name: "David Lee",
    email: "david.lee@example.com",
    role: "Software Engineer",
    manager_id: 2,
  },
  {
    id: 5,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    full_name: "Emily Davis",
    email: "emily.davis@example.com",
    role: "Data Scientist",
    manager_id: 2,
  },
  {
    id: 6,
    image: null,
    full_name: "Sarah Miller",
    email: "sarah.miller@example.com",
    role: "Project Coordinator",
    manager_id: 1,
  },
  {
    id: 7,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    full_name: "Robert Brown",
    email: "robert.brown@example.com",
    role: "Backend Developer",
    manager_id: 1,
  },
  {
    id: 8,
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    full_name: "Anna Wilson",
    email: "anna.wilson@example.com",
    role: "QA Engineer",
    manager_id: 2,
  },
  {
    id: 9,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    full_name: "James Taylor",
    email: "james.taylor@example.com",
    role: "DevOps Engineer",
    manager_id: 1,
  },
  {
    id: 10,
    image: null,
    full_name: "Linda Martinez",
    email: "linda.martinez@example.com",
    role: "Technical Writer",
    manager_id: 2,
  },
];
